### ISSUE TITLE
How to exclude existing records from Saltrun?

### ISSUE THREAD

**Issue by awlx** [cloudflare/salt-cloudflare#12]
Hi everyone,

we (FreifunkMünchen) have a set of existing records in our domain, which we don't want to manage via salt like at all. So they also won't show up in any pillar or something. Is it possible to exclude those from being updated?

I found the "managed" field but didn't find so far how to handle existing records which I don't have in the pillar.

Thanks so much!

**Comment by bobrik** [comment]
You can `exclude` domains from management with a regexp:

* https://github.com/cloudflare/salt-cloudflare/commit/c02057e282a976477

```yaml
cloudflare_zones:
  example.com:
    auth_email: ivan@example.com
    zone_id: 0101deadbeefdeadbeefdeadbeefdead
    exclude:
      - '[^.]+\.unmanaged-subdomains\.example\.com'
    records:
      # ...
```

Hope that helps.
